### PR TITLE
Code/js/loop

### PR DESCRIPTION
**Pull request by ntohidi**
Ready to be merged

### CODE REVIEW

**Comment by unclecode** [comment]
R U OK?!!? You haven't done anything on task 2 and 3! 🤨

**Comment by ntohidi** [comment]
> R U OK?!!? You haven't done anything on task 2 and 3! 🤨

Oh ok ok u right shame on me

**Comment by unclecode** [comment]
so I close this request and make changes and make a new request

**Comment by ntohidi** [comment]
sure

**Pull request closed without merging**
